### ISSUE TITLE
ERROR: the object has been modified; please apply your changes to the latest version and try again

### ISSUE THREAD

**Issue by alexnaris** [Fred78290/kubernetes-vmware-autoscaler#8]
Hello,

Once in a while I get "the object has been modified; please apply your changes to the latest version and try again" error when autoscaling.  During this time the vm is created but something fails (when adding to k8s cluster?) and vm gets deleted.

```
time="2021-09-14T15:49:07Z" level=info msg="Launch VM:dev-k8s-as-vm-16 for nodegroup: dev-k8s-as"
time="2021-09-14T15:51:02Z" level=info msg="Wait kubernetes node dev-k8s-as-vm-16 to be ready"
time="2021-09-14T15:51:12Z" level=info msg="The kubernetes node dev-k8s-as-vm-16 is Ready"
time="2021-09-14T15:51:12Z" level=error msg="Unable to launch VM:dev-k8s-as-vm-16 for nodegroup: dev-k8s-as. Reason: set labels on node: dev-k8s-as-vm-16 got error: Operation cannot be fulfilled on nodes \"dev-k8s-as-vm-16\": the object has been modified; please apply your changes to the latest version and try again"
time="2021-09-14T15:51:12Z" level=error msg="unable to launch the VM owned by node: dev-k8s-as-vm-16, reason: set labels on node: dev-k8s-as-vm-16 got error: Operation cannot be fulfilled on nodes \"dev-k8s-as-vm-16\": the object has been modified; please apply your changes to the latest version and try again"
time="2021-09-14T15:51:15Z" level=info msg="Deleted VM:dev-k8s-as-vm-16"
```
Any ideas what the issue is?

**Comment by Fred78290** [comment]
Hello.

Which version of vmware auscaler are you using?

**Comment by alexnaris** [comment]
I am using the following branch

https://github.com/Fred78290/kubernetes-vmware-autoscaler/tree/fix-autostart

**Comment by Fred78290** [comment]
> I am using the following branch
> 
> 
> 
> https://github.com/Fred78290/kubernetes-vmware-autoscaler/tree/fix-autostart

The k8s version 1.21, I suppose?

The error is inside the kubernetes cluster and globally it means that the label and annotation phase was rejected by apiserver. I will googled the error and find the real reason.
So the VM is deleted because the global process to scale a k8s node doesn't meet my requirements.

additionally it was the 16th VM created keeping the 15st VM alive or your in a loop "scale up scale down" ?
regards

**Comment by alexnaris** [comment]
> The k8s version 1.21, I suppose?

I am actually using v1.21.2.  

> additionally it was the 16th VM created keeping the 15st VM alive or your in a loop "scale up scale down" ?

I was in a scale up / scale down loop.  That actually brings me to another question, is it possible to reset the vm number or does it just keep on going up?

**Comment by alexnaris** [comment]
ok even after recreating the cluster with v1.21.1, I still got the error and now I think I know why this is happening.  it looks like this issue sometimes happens when a previous cluster created a virtual machine with the same name. 

I just got exact same error after creating a new cluster, testing auto-scalling, completely removing and recreating the cluster and testing autoscaling again


as a separate note I just got the following error soon after (using the official Fred78290 image)
```
panic: sync: negative WaitGroup counter

goroutine 2177 [running]:
sync.(*WaitGroup).Add(0xc0001610a0, 0x2)
	/usr/local/go/src/sync/waitgroup.go:74 +0x105
sync.(*WaitGroup).Done(...)
	/usr/local/go/src/sync/waitgroup.go:99
github.com/Fred78290/kubernetes-vmware-autoscaler/server.(*AutoScalerServerNodeGroup).addNodes(0xc0000f74d0, {0x201acd8, 0xc000300ae0}, 0x5)
	/gopath/src/github.com/Fred78290/vsphere-autoscaler/server/nodegroup.go:208 +0x83c
github.com/Fred78290/kubernetes-vmware-autoscaler/server.(*AutoScalerServerNodeGroup).setNodeGroupSize(0xc0000f74d0, {0x201acd8, 0xc000300ae0}, 0x6)
	/gopath/src/github.com/Fred78290/vsphere-autoscaler/server/nodegroup.go:97 +0xe5
github.com/Fred78290/kubernetes-vmware-autoscaler/server.(*AutoScalerServerApp).IncreaseSize(0xc0004543c0, {0xc000091f90, 0x4ec9e6}, 0xc000091f90)
	/gopath/src/github.com/Fred78290/vsphere-autoscaler/server/server.go:718 +0x331
github.com/Fred78290/kubernetes-vmware-autoscaler/grpc._NodeGroupService_IncreaseSize_Handler({0x1ce11e0, 0xc0004543c0}, {0x1fe9580, 0xc00069aa20}, 0xc0005152c0, 0x0)
	/gopath/src/github.com/Fred78290/vsphere-autoscaler/grpc/grpc.pb.go:6222 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004f5a00, {0x2011298, 0xc000322480}, 0xc000967d00, 0xc00059db30, 0x2fd0ca8, 0x0)
	/gopath/src/github.com/Fred78290/vsphere-autoscaler/vendor/google.golang.org/grpc/server.go:1082 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc0004f5a00, {0x2011298, 0xc000322480}, 0xc000967d00, 0x0)
	/gopath/src/github.com/Fred78290/vsphere-autoscaler/vendor/google.golang.org/grpc/server.go:1405 +0x9f3
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	/gopath/src/github.com/Fred78290/vsphere-autoscaler/vendor/google.golang.org/grpc/server.go:746 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/gopath/src/github.com/Fred78290/vsphere-autoscaler/vendor/google.golang.org/grpc/server.go:744 +0xef
```

**Comment by Fred78290** [comment]
> I was in a scale up / scale down loop. That actually brings me to another question, is it possible to reset the vm number or does it just keep on going up?

No it's not allowed to reset the vm number. I had the choice to generate a random GUID for the VM or use an incremental number, I choose the incremental number.

> I just got exact same error after creating a new cluster, testing auto-scalling, completely removing and recreating the cluster and testing autoscaling again

Are you sure that all VM from the previous cluster was destroyed on you vsphere? Because I'm not able to create a VM with the same name

> panic: sync: negative WaitGroup counter

Strange. It's will be difficult to find this error. 

To help me, could you describe exactly what you are doing during your test (wording, screen short, ...)

I've tested until 10 vm created, also I'm resources limited because my vsphere is virtualized :)

Regards

**Comment by alexnaris** [comment]
> Are you sure that all VM from the previous cluster was destroyed on you vsphere? Because I'm not able to create a VM with the same name

Yes, everything from the previous test was in fact destroyed...

> To help me, could you describe exactly what you are doing during your test (wording, screen short, ...)

Below is a full log from a test that just failed.  So I completely removed the masterkube and other vms and created everything from scratch.  

So k8s-vm-01 and k8s-vm-02 could not come up because my DHCP server run out of leases..  However, that caused the script to go into a weird loop and eventually panic.  PS vm3 to vm9 were never actually created on VSphere so I am not sure why script tried deleting them



```
time="2021-09-16T20:14:38Z" level=info msg="config: APIServerURL: KubeConfig: RequestTimeout:2m0s Config:/etc/cluster/kubernetes-vmware-autoscaler.json SaveLocation:/var/run/cluster-autoscaler/vmware-autoscaler-state.json DisplayVersion:false"
time="2021-09-16T20:14:38Z" level=info msg="Instantiating new Kubernetes client"
time="2021-09-16T20:14:38Z" level=info msg="Using inCluster-config based on serviceaccount-token"
time="2021-09-16T20:14:38Z" level=info msg="Created Kubernetes client https://10.96.0.1:443"
time="2021-09-16T20:14:38Z" level=info msg="Start listening server on /var/run/cluster-autoscaler/vmware.sock"
time="2021-09-16T20:14:57Z" level=info msg="Auto provision for nodegroup:k8s, minSize:0, maxSize:15"
time="2021-09-16T20:14:57Z" level=info msg="New node group, ID:k8s minSize:0, maxSize:15, machineType:grs-custom, node lables:map[cluster.autoscaler.nodegroup/name:k8s], map[node-role.kubernetes.io/worker:]"
time="2021-09-16T20:14:57Z" level=info msg="Discover node:vmware://k8s/object?type=node&name=k8s-masterkube matching nodegroup:k8s"
time="2021-09-16T20:14:57Z" level=info msg="Add node:k8s-masterkube with IP:10.52.32.10 to nodegroup:k8s"
time="2021-09-16T20:15:08Z" level=info msg="Launch VM:k8s-vm-01 for nodegroup: k8s"
time="2021-09-16T20:17:01Z" level=info msg="Wait kubernetes node k8s-vm-01 to be ready"
time="2021-09-16T20:17:11Z" level=info msg="The kubernetes node k8s-vm-01 is Ready"
time="2021-09-16T20:17:12Z" level=info msg="Launched VM:k8s-vm-01 for nodegroup: k8s"
time="2021-09-16T20:17:12Z" level=info msg="Launch VM:k8s-vm-02 for nodegroup: k8s"
time="2021-09-16T20:23:21Z" level=error msg="Unable to launch VM:k8s-vm-02 for nodegroup: k8s. Reason: could not start VM: k8s-vm-02, reason: Post \"https://vcenter.local/sdk\": context deadline exceeded"
time="2021-09-16T20:23:21Z" level=error msg="unable to launch the VM owned by node: k8s-vm-02, reason: could not start VM: k8s-vm-02, reason: Post \"https://vcenter.local/sdk\": context deadline exceeded"
time="2021-09-16T20:23:26Z" level=info msg="Deleted VM:k8s-vm-01"
time="2021-09-16T20:23:29Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-01, reason: vm 'k8s-vm-01' not found"
time="2021-09-16T20:23:40Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-01, reason: vm 'k8s-vm-01' not found"
time="2021-09-16T20:23:50Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-01, reason: vm 'k8s-vm-01' not found"
time="2021-09-16T20:24:02Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-01, reason: vm 'k8s-vm-01' not found"
time="2021-09-16T20:24:13Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-01, reason: vm 'k8s-vm-01' not found"
time="2021-09-16T20:24:25Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-01, reason: vm 'k8s-vm-01' not found"
time="2021-09-16T20:24:36Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-01, reason: vm 'k8s-vm-01' not found"
time="2021-09-16T20:24:47Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-01, reason: vm 'k8s-vm-01' not found"
time="2021-09-16T20:24:58Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-01, reason: vm 'k8s-vm-01' not found"
time="2021-09-16T20:25:09Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-01, reason: vm 'k8s-vm-01' not found"
time="2021-09-16T20:25:20Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-01, reason: vm 'k8s-vm-01' not found"
time="2021-09-16T20:25:31Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-01, reason: vm 'k8s-vm-01' not found"
time="2021-09-16T20:25:42Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-01, reason: vm 'k8s-vm-01' not found"
time="2021-09-16T20:25:54Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-01, reason: vm 'k8s-vm-01' not found"
time="2021-09-16T20:26:05Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-01, reason: vm 'k8s-vm-01' not found"
time="2021-09-16T20:26:16Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-01, reason: vm 'k8s-vm-01' not found"
time="2021-09-16T20:26:27Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-01, reason: vm 'k8s-vm-01' not found"
time="2021-09-16T20:26:38Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-01, reason: vm 'k8s-vm-01' not found"
time="2021-09-16T20:26:49Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-01, reason: vm 'k8s-vm-01' not found"
time="2021-09-16T20:27:00Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-01, reason: vm 'k8s-vm-01' not found"
time="2021-09-16T20:27:11Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-01, reason: vm 'k8s-vm-01' not found"
time="2021-09-16T20:27:22Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-01, reason: vm 'k8s-vm-01' not found"
time="2021-09-16T20:27:33Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-01, reason: vm 'k8s-vm-01' not found"
time="2021-09-16T20:27:44Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-01, reason: vm 'k8s-vm-01' not found"
time="2021-09-16T20:27:55Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-01, reason: vm 'k8s-vm-01' not found"
time="2021-09-16T20:28:06Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-01, reason: vm 'k8s-vm-01' not found"
time="2021-09-16T20:28:17Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-01, reason: vm 'k8s-vm-01' not found"
time="2021-09-16T20:28:27Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-02, reason: Post \"https://vcenter.local/sdk\": context deadline exceeded"
time="2021-09-16T20:28:29Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-01, reason: vm 'k8s-vm-01' not found"
time="2021-09-16T20:28:40Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-01, reason: vm 'k8s-vm-01' not found"
time="2021-09-16T20:28:51Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-01, reason: vm 'k8s-vm-01' not found"
time="2021-09-16T20:29:02Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-01, reason: vm 'k8s-vm-01' not found"

time="2021-09-16T20:29:13Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-01, reason: vm 'k8s-vm-01' not found"
time="2021-09-16T20:29:21Z" level=error msg="cordon node: k8s-vm-02 got error: resource name may not be empty"
time="2021-09-16T20:29:21Z" level=error msg="delete node: k8s-vm-02 got error: nodes \"k8s-vm-02\" not found"
time="2021-09-16T20:29:23Z" level=info msg="Deleted VM:k8s-vm-02"
time="2021-09-16T20:29:23Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-03, reason: vm 'k8s-vm-03' not found"
time="2021-09-16T20:29:24Z" level=error msg="Could not delete VM:k8s-vm-03. Reason: vm 'k8s-vm-03' not found"
time="2021-09-16T20:29:24Z" level=error msg="unable to delete the VM owned by node: k8s-vm-03, reason: vm 'k8s-vm-03' not found"
time="2021-09-16T20:29:25Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-04, reason: vm 'k8s-vm-04' not found"
time="2021-09-16T20:29:25Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-01, reason: vm 'k8s-vm-01' not found"
time="2021-09-16T20:29:26Z" level=error msg="Could not delete VM:k8s-vm-04. Reason: vm 'k8s-vm-04' not found"
time="2021-09-16T20:29:26Z" level=error msg="unable to delete the VM owned by node: k8s-vm-04, reason: vm 'k8s-vm-04' not found"
time="2021-09-16T20:29:26Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-05, reason: vm 'k8s-vm-05' not found"
time="2021-09-16T20:29:27Z" level=error msg="Could not delete VM:k8s-vm-05. Reason: vm 'k8s-vm-05' not found"
time="2021-09-16T20:29:27Z" level=error msg="unable to delete the VM owned by node: k8s-vm-05, reason: vm 'k8s-vm-05' not found"
time="2021-09-16T20:29:27Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-06, reason: vm 'k8s-vm-06' not found"
time="2021-09-16T20:29:28Z" level=error msg="Could not delete VM:k8s-vm-06. Reason: vm 'k8s-vm-06' not found"
time="2021-09-16T20:29:28Z" level=error msg="unable to delete the VM owned by node: k8s-vm-06, reason: vm 'k8s-vm-06' not found"
time="2021-09-16T20:29:28Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-07, reason: vm 'k8s-vm-07' not found"
time="2021-09-16T20:29:29Z" level=error msg="Could not delete VM:k8s-vm-07. Reason: vm 'k8s-vm-07' not found"
time="2021-09-16T20:29:29Z" level=error msg="unable to delete the VM owned by node: k8s-vm-07, reason: vm 'k8s-vm-07' not found"
time="2021-09-16T20:29:29Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-08, reason: vm 'k8s-vm-08' not found"
time="2021-09-16T20:29:30Z" level=error msg="Could not delete VM:k8s-vm-08. Reason: vm 'k8s-vm-08' not found"
time="2021-09-16T20:29:30Z" level=error msg="unable to delete the VM owned by node: k8s-vm-08, reason: vm 'k8s-vm-08' not found"
time="2021-09-16T20:29:30Z" level=error msg="can't get the VM info from AutoScaler for VM: k8s-vm-09, reason: vm 'k8s-vm-09' not found"
time="2021-09-16T20:29:31Z" level=error msg="Could not delete VM:k8s-vm-09. Reason: vm 'k8s-vm-09' not found"
time="2021-09-16T20:29:31Z" level=error msg="unable to delete the VM owned by node: k8s-vm-09, reason: vm 'k8s-vm-09' not found"
panic: sync: negative WaitGroup counter

goroutine 96 [running]:
sync.(*WaitGroup).Add(0xc0001c70a0, 0x2)
	/usr/local/go/src/sync/waitgroup.go:74 +0x105
sync.(*WaitGroup).Done(...)
	/usr/local/go/src/sync/waitgroup.go:99
github.com/Fred78290/kubernetes-vmware-autoscaler/server.(*AutoScalerServerNodeGroup).addNodes(0xc0000c73b0, {0x201acd8, 0xc00007e900}, 0x9)
	/gopath/src/github.com/Fred78290/vsphere-autoscaler/server/nodegroup.go:208 +0x83c
github.com/Fred78290/kubernetes-vmware-autoscaler/server.(*AutoScalerServerNodeGroup).setNodeGroupSize(0xc0000c73b0, {0x201acd8, 0xc00007e900}, 0xa)
	/gopath/src/github.com/Fred78290/vsphere-autoscaler/server/nodegroup.go:97 +0xe5
github.com/Fred78290/kubernetes-vmware-autoscaler/server.(*AutoScalerServerApp).IncreaseSize(0xc0000919f0, {0xc0001e6190, 0x4ec9e6}, 0xc0001e6190)
	/gopath/src/github.com/Fred78290/vsphere-autoscaler/server/server.go:718 +0x331
github.com/Fred78290/kubernetes-vmware-autoscaler/grpc._NodeGroupService_IncreaseSize_Handler({0x1ce11e0, 0xc0000919f0}, {0x1fe9580, 0xc000098d20}, 0xc00046d140, 0x0)
	/gopath/src/github.com/Fred78290/vsphere-autoscaler/grpc/grpc.pb.go:6222 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000330000, {0x2011298, 0xc000320a80}, 0xc00017b600, 0xc0004d1500, 0x2fd0ca8, 0x0)
	/gopath/src/github.com/Fred78290/vsphere-autoscaler/vendor/google.golang.org/grpc/server.go:1082 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc000330000, {0x2011298, 0xc000320a80}, 0xc00017b600, 0x0)
	/gopath/src/github.com/Fred78290/vsphere-autoscaler/vendor/google.golang.org/grpc/server.go:1405 +0x9f3
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	/gopath/src/github.com/Fred78290/vsphere-autoscaler/vendor/google.golang.org/grpc/server.go:746 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/gopath/src/github.com/Fred78290/vsphere-autoscaler/vendor/google.golang.org/grpc/server.go:744 +0xef
```

**Comment by Fred78290** [comment]
Well the reason is that vmware-autoscaler can't communicate with the VM because DHCP is out of stock of IP.

Also the kubernetes autoscaler will try every time to satisfy the kubernetes scheduler to scale up pods but the vmware autoscaler can't do that because DHCP problems.

So I understand now, but difficult to reproduce the problem.

**Comment by alexnaris** [comment]
here is another example and DHCP was not the issue here.  Virtual machine definitely came up with an IP

```
time="2021-09-16T21:34:07Z" level=info msg="Deleted VM:k8s-vm-14"

time="2021-09-17T13:19:41Z" level=info msg="Launch VM:k8s-vm-15 for nodegroup: k8s"
time="2021-09-17T13:21:30Z" level=info msg="Wait kubernetes node k8s-vm-15 to be ready"
time="2021-09-17T13:21:50Z" level=info msg="The kubernetes node k8s-vm-15 is Ready"
time="2021-09-17T13:21:50Z" level=info msg="Launched VM:k8s-vm-15 for nodegroup: k8s"
time="2021-09-17T13:21:50Z" level=info msg="Launch VM:k8s-vm-16 for nodegroup: k8s"
time="2021-09-17T13:23:53Z" level=error msg="Unable to launch VM:k8s-vm-16 for nodegroup: k8s. Reason: can't set provider ID for node: k8s-vm-16, reason: Operation cannot be fulfilled on nodes \"k8s-vm-16\": the object has been modified; please apply your changes to the latest version and try again"
time="2021-09-17T13:23:53Z" level=error msg="unable to launch the VM owned by node: k8s-vm-16, reason: can't set provider ID for node: k8s-vm-16, reason: Operation cannot be fulfilled on nodes \"k8s-vm-16\": the object has been modified; please apply your changes to the latest version and try again"
time="2021-09-17T13:23:58Z" level=info msg="Deleted VM:k8s-vm-15"
time="2021-09-17T13:24:06Z" level=info msg="Deleted VM:k8s-vm-16"
panic: sync: negative WaitGroup counter

goroutine 305308 [running]:
sync.(*WaitGroup).Add(0xc000412480, 0x201acd8)
        /usr/local/go/src/sync/waitgroup.go:74 +0x105
sync.(*WaitGroup).Done(...)
        /usr/local/go/src/sync/waitgroup.go:99
github.com/Fred78290/kubernetes-vmware-autoscaler/server.(*AutoScalerServerNodeGroup).addNodes(0xc0000c4240, {0x201acd8, 0xc0004b4c60}, 0x2)
        /gopath/src/github.com/Fred78290/vsphere-autoscaler/server/nodegroup.go:208 +0x83c
github.com/Fred78290/kubernetes-vmware-autoscaler/server.(*AutoScalerServerNodeGroup).setNodeGroupSize(0xc0000c4240, {0x201acd8, 0xc0004b4c60}, 0x3)
        /gopath/src/github.com/Fred78290/vsphere-autoscaler/server/nodegroup.go:97 +0xe5
github.com/Fred78290/kubernetes-vmware-autoscaler/server.(*AutoScalerServerApp).IncreaseSize(0xc000469c20, {0xc00113d6d0, 0x4ec9e6}, 0xc00113d6d0)
        /gopath/src/github.com/Fred78290/vsphere-autoscaler/server/server.go:718 +0x331
github.com/Fred78290/kubernetes-vmware-autoscaler/grpc._NodeGroupService_IncreaseSize_Handler({0x1ce11e0, 0xc000469c20}, {0x1fe9580, 0xc000d19290}, 0xc0009e5d40, 0x0)
        /gopath/src/github.com/Fred78290/vsphere-autoscaler/grpc/grpc.pb.go:6222 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000107a00, {0x2011298, 0xc0000de480}, 0xc00076ee00, 0xc00044daa0, 0x2fd0ca8, 0x0)
        /gopath/src/github.com/Fred78290/vsphere-autoscaler/vendor/google.golang.org/grpc/server.go:1082 +0xc8f
google.golang.org/grpc.(*Server).handleStream(0xc000107a00, {0x2011298, 0xc0000de480}, 0xc00076ee00, 0x0)
        /gopath/src/github.com/Fred78290/vsphere-autoscaler/vendor/google.golang.org/grpc/server.go:1405 +0x9f3
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        /gopath/src/github.com/Fred78290/vsphere-autoscaler/vendor/google.golang.org/grpc/server.go:746 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /gopath/src/github.com/Fred78290/vsphere-autoscaler/vendor/google.golang.org/grpc/server.go:744 +0xef
```

**Comment by Fred78290** [comment]
Hello I have reproduced this error in my environment, it's took a long time to reproduce 16 vm before the error occurs.

The problem looks like this one: https://github.com/kubernetes/kubernetes/issues/84430

So I have created a branch named fix-issue-8, It's not fully tested now. If you want start a test in your environment, it will be cool.

The next step will be to fix the panic waitgroup become negative, I see where the problem is located but unable to reproduce it.

Regards

**Comment by Fred78290** [comment]
Hello again, i have add some enhanced code to allow deploy node in parallel and in facto remove the waitgroup panic.

Regards

**Comment by Fred78290** [comment]
After some test stress, the fix is working.

**Comment by alexnaris** [comment]
Sorry for the delay and thank you for the fix!   I will check out fix-issue-8 branch, give it an aggressive test run and report back

**Comment by Fred78290** [comment]
Thank you for help.

Please test branch v1.21, because I have merged and fixed another bug (pull request #10). The docker repo will be updated in few minutes (action running)

**Comment by Fred78290** [comment]
> question in regards to node depoy in parallel, is there a variable to limit how many nodes can be done in parallel?
Effectively, I messed this option :+1: 

> as for testing v1.21 and #10 bug I will test tomorrow but I am not sure if it fits my scenario as I use DCHP for all worker nodes

This fix will avoid to have an out of stock of IP address with DHCP server, don't forget to specify "generate" for mac-address field in interface declaration

**Comment by alexnaris** [comment]
> Effectively, I messed this option 👍
:)

> This fix will avoid to have an out of stock of IP address with DHCP server, don't forget to specify "generate" for mac-address field in interface declaration

it looks like your fix is actually working and a mac address does get reused.  However, my DCHP server hands out a different IP which is probably the an issue with my dhcp server not the code..

<img width="220" alt="Screen Shot 2021-09-23 at 4 36 18 PM" src="https://user-images.githubusercontent.com/3943257/134580116-af4fd8e8-8df4-4c4a-9724-7a65f02da680.png">

PS.  I am away until Monday but will do more testing when I come back.  but so far v1.21 is looking good
